---
jenkins_version: ''
jenkins_hostname: 'localhost'
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_plugins:
  - cloudbees-folder
  - gradle
  - ws-cleanup
  - timestamper
  - git-client
  - github-branch-source
  - git
  - gitlab-plugin
  - workflow-aggregator
  - htmlpublisher
  - testng-plugin
  - influxdb
  - blueocean
  - locale
  - monitoring
  - email-ext
  - simple-theme-plugin
  - warnings
  - sonar
  - build-user-vars-plugin

admin:
  username: admin
  password_hash: salt:8ce9635a5c70fefbd4832ae40a57fd0c75e340f181c70ba10f4e08e50038c974
  password: test123

jenkins_users:
  tester:
    password: qwerty123
  
jenkins_credentials:
  git_user:
    template_name: user_publickey.j2
    name: git_user_to_pull_code

jenkins_jobs:
  static_pipeline_job_example:
    job_template: static_pipeline_git.j2
    job_name: static_job_name
    git_repo: git_repo_url
    git_user_id: "{{ jenkins_credentials.git_user.name }}"
    git_branch: master
    script_path: Jenkinsfile path

  scm_poll_job_example:
    git_branch: master
    job_template: scm_poll_job.j2
    job_name: scm_poll_job_name
    git_repo: git_repo_url
    git_user_id: "{{ jenkins_credentials.git_user.name }}"
    git_folder: local-env
    script_path: Jenkinsfile path