---
- name: "Install common tools"
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  become: true
  become_user: root
  with_items:
    - vim
    - python-pip
    - python-dev
    - build-essential
    - default-jdk
    - curl
    - apt-transport-https
  tags: base