grafana_version: latest
grafana_admin: grafana_admin
grafana_pass: qwerty123

grafana_logs_dir: "/var/log/grafana"
grafana_data_dir: "/var/lib/grafana"

grafana_port: 3000
grafana:
  plugins:
    - briangann-gauge-panel
    - grafana-piechart-panel